export const ActionsEnum = {
    SHOW_MENU: 'SHOW_MENU',
    SHOW_BULLETIN: 'SHOW_BULLETIN',
    SHOW_REGISTRATION: 'SHOW_REGISTRATION',
    SHOW_REGISTRATIONCODE: 'SHOW_REGISTRATIONCODE',
    SHOW_EMAILTEACHERS: 'SHOW_EMAILTEACHERS',
    SHOW_FEEDBACK: 'SHOW_FEEDBACK',
    SHOW_DONATION: 'SHOW_DONATION'
};
